export interface CountryResponse {
	value: string;
	label: string;
}

export interface PokemonUser {
	label: string;
	value: string;
}

export interface UserResponse {
	name: string;
	email: string;
	phone: string;
	password: string;
	dateBirth: string;
	country: string;
	pokemon: PokemonUser | null;
}

// Generated by https://quicktype.io

export interface PokemonResponse {
	count:    number;
	next:     string;
	previous: null;
	results:  Result[];
}

export interface Result {
	name: string;
	url:  string;
}
